### ISSUE TITLE
More content please

### ISSUE THREAD

**Issue by JoshuaGross** [sciolizer/sciolizer.github.io#1]
Hello! I would like to hear more of your thoughts please sir

**Comment by sciolizer** [comment]
+1

i reley dont wan to say this, but I have to now. concept is good, but needs more content. will give 5 stars after this is fixed, but only 2 stars until then. not sure if dev is lazy or what.

**Comment by sciolizer** [comment]
A'ight. Put something up. It's just a copy of joshua.ball.name though.
